### ISSUE TITLE
How can we use a webjar like that with the locator ?

### ISSUE THREAD

**Issue by onigoetz** [webjars/globalize#2]
Hi guys,

First, thank you very much for all you do ! you save us litteraly hours every week in javascript asset handling. it's awesome.

I have a question one how to use this webjar in conjunction with the locator.

I get that the simple usage is 

``` java
String fullPathToRequirejs = locator.getFullPath("require.js");
```

That's quite easy, I want requirejs, I tell it to look for `"require.js"`

Now for globalize, there are 8 files
- globalize.js
- date.js
- message.js
- number.js
- ...

The problem I have with that is that the names are pretty generic and might collide with other webjar's names.

So what do I get if I do that ?

``` java
String fullPathToRequirejs = locator.getFullPath("date.js");
```

Even worse, in the npm version of the `globalize` package, there is both `src/date.js` and `dist/date.js` and `src/date.js` is really not made for a browser.

So my questions : 
- Is there a way to be sure that a file comes from a specific webjar ? something like `getFullPath("globalize/date.js")` or `getFullPath("globalize", "date.js")`
- Is there a way to ignore some folders when doing the location ? like "test" and "src" (or some affinity, prefer files from a "dist" folder but fallback to "src" if it doesn't exist ?

Thank you in advance for your answer.

**Comment by jamesward** [comment]
I've added some additional docs on using the locator:
https://github.com/webjars/webjars-locator-core

Let me know if that helps.

**Comment by onigoetz** [comment]
That should help, yes

Thank you :D
